---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sb8200-exporter
  namespace: metrics
  labels:
    app.kubernetes.io/name: sb8200-exporter
    app.kubernetes.io/instance: sb8200-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sb8200-exporter
      app.kubernetes.io/instance: sb8200-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sb8200-exporter
        app.kubernetes.io/instance: sb8200-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: webdriver
          image: selenium/standalone-chrome
          ports:
            - name: http
              containerPort: 4444
          resources: {}
        - name: sb8200-exporter
          image: sb8200_exporter:latest
          env:
            - name: MODEM_PASS
              valueFrom:
                secretKeyRef:
                  name: sb8200-exporter
                  key: password
          ports:
            - name: metrics
              containerPort: 9195
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
      - name: docker