---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sb8200-exporter-secret
  namespace: metrics
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sb8200-exporter
  data:
  - secretKey: password
    remoteRef:
      key: kubernetes/modem-infra
      property: sb8200-exporter-password 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-secret
  namespace: metrics
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: kubernetes/docker-infra
      property: dockerconfig.json
  