{
 "title": "Cable Modem",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Downstream Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sb8200_downstream_power",
     "legendFormat": "Ch {{channel_id}} --- {{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sb8200_downstream_snr_mer",
     "legendFormat": "ch {{channel_id}} --- {{frequency}}"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(sb8200_upstream_power) by (frequency)",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Corrected Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(sb8200_downstream_corrected_total[5m])",
     "legendFormat": "Ch {{channel_id}} --- {{frequency}}"
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sb8200_downstream_uncorrectables_total[5m])",
     "legendFormat": "Ch {{channel_id}} --- {{frequency}}"
    }
   ]
  },
  {
   "title": "Modem Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "sb8200_state" }
   ]
  }
 ]
}