name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  build:

    runs-on: self-hosted, x64

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo Code

    - uses: azure/docker-login@v1
      with:
        login-server: core.harbor.v.gallis.cloud
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        docker build --network=host -t core.harbor.v.gallis.cloud/east/${{ secrets.IMAGE_NAME }}:latest .
        docker push core.harbor.v.gallis.cloud/east/${{ secrets.IMAGE_NAME }}:latest
      
    - uses: 8398a7/action-slack@v3
      name: Slack Notification
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
